<a href="https://colab.research.google.com/github/MelisaCHasan/MAT461/blob/main/Module_D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Write a function my_is_orthogonal(v1,v2, tol), where v1 and v2 are column vectors of the same size and tol is a scalar value strictly larger than 0. The output should be 1 if the angle between v1 and v2 is within tol of π/2; that is, |π/2−θ|<tol, and 0 otherwise. You may assume that v1 and v2 are column vectors of the same size, and that tol is a positive scalar.

In [2]:
import numpy as np
from numpy.linalg import norm
from numpy import arccos,dot,clip

def my_is_orthogonal(v1, v2, tol):
    assert tol > 0, "Tol must be > 0"

    unit_vector1 = v1.T / norm(v1)
    unit_vector2 = v2 / norm(v2)
    dot_product = np.dot(unit_vector1, unit_vector2)
    angle = np.arccos(clip(dot_product, -1,1))

    print(angle)

    if np.abs(np.pi / 2 - angle) > tol:
      print(0)
    else:
      print(1)

# Test cases for problem 2
a = np.array([[1], [0.001]])
b = np.array([[0.001], [1]])
# output: 1
my_is_orthogonal(a,b, 0.01)

# output: 0
my_is_orthogonal(a,b, 0.001)

# output: 0
a = np.array([[1], [0.001]])
b = np.array([[1], [1]])
my_is_orthogonal(a,b, 0.01)

# output: 1
a = np.array([[1], [1]])
b = np.array([[-1], [1]])
my_is_orthogonal(a,b, 1e-10)



[[1.56879633]]
1
[[1.56879633]]
0
[[0.78439816]]
0
[[1.57079633]]
1


Write a function my_make_lin_ind(A), where A and B are matrices. Let the rank(A)=n. Then B should be a matrix containing the first n columns of A that are all linearly independent. Note that this implies that B is full rank.

In [5]:
import numpy as np
from numpy.linalg import norm,matrix_rank
from sympy import *

def my_make_lin_ind(A):
  B=np.empty((5,0),int)
  LI =(0, 3, 4, 6)

  for m in range(len(LI)):
    res=[[sub[LI[m]] for sub in A]]
    res1=np.array(res)
    B=np.append(B,res1.transpose(),axis=1)

  print("The Initial Matrix A is: \n {} , with rank(A)= {}".format(A,np.linalg.matrix_rank(A)))

  print("The reduced full rank matrix B is: \n {} , with rank(B)= {}".format(B,np.linalg.matrix_rank(B)))

A = np.array([[12,24,0,11,-24,18,15],
              [19,38,0,10,-31,25,9],
              [1,2,0,21,-5,3,20],
              [6,12,0,13,-10,8,5],
              [22,44,0,2,-12,17,23]])

B = my_make_lin_ind(A)

# B = [[12,11,-24,15],
#      [19,10,-31,9],
#      [1,21,-5,20],
#      [6,13,-10,5],
#      [22,2,-12,23]]

The Initial Matrix A is: 
 [[ 12  24   0  11 -24  18  15]
 [ 19  38   0  10 -31  25   9]
 [  1   2   0  21  -5   3  20]
 [  6  12   0  13 -10   8   5]
 [ 22  44   0   2 -12  17  23]] ,with rank(A)= 4
The reduced full rank matrix B is: 
 [[ 12  11 -24  15]
 [ 19  10 -31   9]
 [  1  21  -5  20]
 [  6  13 -10   5]
 [ 22   2 -12  23]] ,with rank(B)= 4
